version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      TZ: Europe/Paris
    networks:
      - ace-bridged
    volumes:
      - db:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - ace-bridged
    depends_on:
      - db

  backend:
    image: therealhoko/pcs-backend:1.0.0
    restart: always
    env_file:
      - ./ace/.env.local
    ports:
      - 3000:3000
    networks:
      - ace-bridged
    depends_on:
      - db

  frontend:
    image: therealhoko/pcs-frontend:1.0.0
    restart: always
    ports:
      - 80:80
    networks:
      - ace-bridged
    depends_on:
      - backend
  
volumes:
  db:

networks:
  ace-bridged:
    driver: bridge