version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      TZ: Europe/Paris
    volumes:
      - db:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db

  # frontend:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./frontend:/usr/share/nginx/html
  #   depends_on:
  #     - db
  
  # backend:
  #   image: node:latest
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend:/var/www/html
  #   depends_on:
  #     - db
volumes:
  db: