export enum RoleEnum {
  ADMIN = 'ADMIN',
  TRAVELER = 'TRAVELER',
  PROVIDER = 'PROVIDER',
  LESSOR = 'LESSOR',
  FREE_TIER = 'FREE_TIER',
  BAG_PACKER = 'BAG_PACKER',
  EXPLORATOR = 'EXPLORATOR',
}
